### ISSUE TITLE
javadebug-agent-launch

### ISSUE THREAD

**Issue by niujianlong** [pandening/Java-debug-tool#11]
./javadebug-agent-launch.sh 71566
运行后出现这样的报错是什么原因呢？
Exception in thread "main" java.lang.NullPointerException
	at io.javadebug.core.log.PSLogger.error(PSLogger.java:109)
	at io.javadebug.core.JavaDebugLauncher.main(JavaDebugLauncher.java:186)

**Comment by pandening** [comment]
你首先需要通过 javadebug-agent-launch.sh 这个脚本挂载到目标JVM上启动调试器，才能执行后续的流程，可以看一下首页的文档，有比较详细的介绍。
